# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc9452196c3d3e0a9ef694840816f8bd31023e9bb09908968c2ed80d3dc1c63f596ace4de2a638fefcc64e0a9ed75c2cbe82c8034361b6ffb0a81e4ec4065aad

test:
  secret_key_base: 0243a06127f4937d8647050d4f0987aaec96bffb4f8e779b8498ec1b039b4e4bfbaa33ef47bef6d512debd2e44d7ae195124ba9f4d54036bb616404e3a4d35a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
